---
abstract: 'Generate and compare checksums of database schematas'
author:
  - 'Thomas Klausner <domm@cpan.org>'
  - 'Maroš Kollár <maros@cpan.org>'
  - 'Klaus Ita <koki@worstofall.com>'
build_requires:
  DBD::SQLite: 1.35
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  Module::Build: 0.3601
  Module::Pluggable: 0
  Test::More: 0
  Test::Most: 0
  Test::Trap: 0
  lib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-SchemaChecksum
requires:
  Carp: 0
  DBI: 0
  Data::Dumper: 0
  Digest::SHA1: 0
  File::Find::Rule: 0
  IO::Prompt::Tiny: 0
  Moose: 0
  Moose::Role: 0
  MooseX::App: 1.21
  MooseX::App::Command: 0
  Path::Class: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  utf8: 0
  warnings: 0
resources:
  repository: git://devbox.vpn.validad.net/DBIx-SchemaChecksum.git
version: 1.004
